### ISSUE TITLE
Improve search interface on Bugs by publisher page

### ISSUE THREAD

**Issue by YohannaLoucheur** [VincentVW/iati_bugs#6]
1) Make search boxes more obvious
I didn't realize until the 3rd pass that I could type something above the column Publisher ref or Publisher name to search a specific one. 

2) Provide "sort" button for all columns
It would be nice to be able to click at the top of each column to order them alphabetically. It's not immediately obvious they are ordered by bug count (nor is it particularly useful if the main audience is individual reporters).

**Comment by VincentVW** [comment]
@YohannaLoucheur should also be fixed, sort works on reference & name (not on bug count for tech reasons, but its not that important anyway).
